import express from 'express';
import { requireAuth } from '../middleware/auth.js';
import { prisma } from '../db.js';
const router = express.Router();
router.use(requireAuth);
router.get('/', async (_req, res) => res.json(await prisma.piece.findMany({ orderBy: { name: 'asc' } })));
router.post('/', async (req, res) => res.status(201).json(await prisma.piece.create({ data: req.body })));
router.put('/:id', async (req, res) => res.json(await prisma.piece.update({ where: { id: req.params.id }, data: req.body })));
router.delete('/:id', async (req, res) => { await prisma.piece.delete({ where: { id: req.params.id } }); res.status(204).end(); });
export default router;
